### PR TITLE
Fourt: Add transcription of the fourt function

### PR DESCRIPTION
**Pull request by TobyAsE**
This is the start of the function FOURT

I found one version from the ESO, which is very clearly based on the same code but at the same time clearly not the same https://ftp.eso.org/scisoft/scisoft4/sources/iraf/extern/stsdas/pkg/playpen/ils/fourt.f

### CODE REVIEW

**Comment by ruenahcmohr** [comment]
OOooh it looks like it was just a random file pulled to play with a versioning system.....

**Comment by TobyAsE** [comment]
It's part of scisoft4 archived by eso
-> which includes iraf, an astronomy data processing software package
-> which includes stsdas, the software suite used for data analysis by the Hubble space telescope. This version is V2.2 from August 2000 or V2.3 from 2001
-> the fourt.f is part of a iterative least squares image algorithm by I. Busco, the ils.x file (a configuration for iraf I think) mentions that fft is done by means of Norman Brenner's fourt routine. It was created in 1992 or 1993, the file has a date stamp of 1997.
The help file is from 1994 and it mentions the speed increase by using factors rich in powers of two, for which the fourt is indeed faster than the other fft implementations according to the comments at the top.

This is 25 years later than our printed version and still very very similar!

Interesting archeology!

**Comment by TobyAsE** [comment]
I have now finished manually transcribing the FOURT subroutine, the ESO file was a great help, but it is in the end a bit different.
It compiles and it runs :)

I have also added some test script to test the algorithm.

It does almost work correctly, the output is a bit mixed up: The imaginary part should be multiplied with -1 and appear one entry further down...
```
(4.00000000,2.41421342)
(1.00000000,0.00000000)
(0.00000000,0.414213479)
(0.999999940,0.00000000)
(0.00000000,-0.414213479)
(0.999999940,0.00000000)
(0.00000000,-2.41421342)
(1.00000000,0.00000000)
```

**Comment by ruenahcmohr** [comment]
I had quite a time when I was digging for FOUR1, I found all sorts of modern code that had been carried along thru the ages from the old source. The differences between the ESO version of FOURT and the transcription are rather interesting. I see a few possible errors in the transcription of FOURT and will rake thru it later tonight. Isn't it amazing how this really old source has carried thru almost completely unchanged over 57 years.

**Comment by olebole** [comment]
Just one comment here: This file does not originate from ESO. It is part of the "STSDAS" IRAF package that was maintained by STScI. See here for an STScI reference: https://github.com/spacetelescope/stsdas_stripped/blob/master/stsdas/pkg/playpen/ils/fourt.f
ESO SciSoft just was a collection of astronomical relevant software with different origin for Redhat systems, which was later adopted for the Mac.

**Pull request merged**
