### PR TITLE
FFT: Transcribe PDF into Fortran Code

### PR DESCRIPTION
**Pull request by TobyAsE**
It builds and it runs without crashing.

I don't really get how to test it.
That was a fun software archeology exercise!

### CODE REVIEW

**Comment by ruenahcmohr** [comment]
translation from TobyAsE!

**Comment by TobyAsE** [comment]
I've found some errors in my transcription, but now it crashes, I will follow up with another PR.

For testing I do the forward and reverse transform and check for the multiplication with NN mentioned in the comments (ln 16f).

**Comment by TobyAsE** [comment]
This was really fun, I'll give it a try!

**Comment by ruenahcmohr** [comment]
That document was super hard to find, so its great to be bringing it back to life.

**Pull request merged**
